TEXTE = {   'en': {   'auth_login': 'Authentication',
              'auth_register': 'Registration',
              'btn_back_dash': 'Back to Dashboard',
              'btn_back_menu': 'Back to Home Page',
              'btn_cancel': 'Cancel',
              'btn_chg_photo': 'Change your profile picture',
              'btn_chg_user': 'Change the username',
              'btn_create': 'Create account',
              'btn_del_acc': 'Delete Account',
              'btn_enter': 'Log in to your account',
              'btn_finish_quiz': 'See Results',
              'btn_main_menu': 'Main Menu',
              'btn_next_q': 'Next',
              'btn_no': 'No',
              'btn_quiz': 'Solve the Quiz',
              'btn_restart': 'Lesson resumes',
              'btn_rst_pass': 'Reset Password',
              'btn_save': 'Save',
              'btn_start': 'Start the Lesson',
              'btn_start_quiz': 'Start the Quiz',
              'btn_theory': 'Read Theory',
              'btn_upload': 'Load',
              'btn_yes_del': 'Yes, Delete',
              'dash_subtitle': 'Learn to detect digital traps step by step.',
              'dash_title': 'Digital Education',
              'js_alert_select': 'Please select at least one option!',
              'js_correct_msg': 'Correct answer!',
              'js_correct_was': 'It was correct:',
              'js_multi_choice': '(Warning: There are more than one correct '
                                 'answer! Select all)',
              'js_single_choice': '(Select only one answer)',
              'js_you_chose': 'You chose:',
              'lbl_new_name': 'New username:',
              'lbl_new_pass': 'New Password:',
              'lbl_old_pass': 'Old Password:',
              'lbl_pass': 'Password',
              'lbl_pick_file': 'Choose an image (jpg, png):',
              'lbl_progress': 'Progress',
              'lbl_question_no': 'The question',
              'lbl_report': 'Detailed Report:',
              'lbl_select_correct': 'Select the correct answer:',
              'lbl_user': 'Username',
              'link_has_acc': 'Already have an account? Login',
              'link_no_acc': "Don't have an account? Sign up",
              'mod_del_title': 'Confirmation',
              'mod_pass_title': 'Reset Password',
              'mod_photo_title': 'Choose Image',
              'mod_user_title': 'Change Username',
              'msg_bravo': 'Congratulations! Here is your result:',
              'msg_del_warn': 'Are you sure? You will lose all progress.',
              'msg_quiz_ready': 'Are you ready to test yourself and get the '
                                'maximum score?',
              'msg_theory_done': 'You went through all the theory!',
              'nav_dashboard': 'Dashboard',
              'nav_lang': 'Language',
              'nav_logout': 'Exit / Log out',
              'nav_scores': 'Scores',
              'nav_settings': 'Account Settings',
              'prof_avg': 'average of all lessons',
              'prof_title': 'Statistics and personal progress',
              'prof_total': 'TOTAL',
              'quiz_page_title': 'Quiz:',
              'set_title': 'Account Setup'},
    'fr': {   'auth_login': 'Authentification',
              'auth_register': 'Inscription',
              'btn_back_dash': 'Retour au tableau de bord',
              'btn_back_menu': 'Retour au menu',
              'btn_cancel': 'Annuler',
              'btn_chg_photo': 'Changez votre photo de profil',
              'btn_chg_user': "Changer le nom d'utilisateur",
              'btn_create': 'Créer un compte',
              'btn_del_acc': 'Supprimer le compte',
              'btn_enter': 'Connectez-vous à votre compte',
              'btn_finish_quiz': 'Voir les résultats',
              'btn_main_menu': 'Menu principal',
              'btn_next_q': 'suivant',
              'btn_no': 'Pas',
              'btn_quiz': 'Résoudre le quiz',
              'btn_restart': 'Reprise des cours',
              'btn_rst_pass': 'Réinitialiser le mot de passe',
              'btn_save': 'Sauvegarder',
              'btn_start': 'La leçon commence',
              'btn_start_quiz': 'Le quiz commence',
              'btn_theory': 'Lire la théorie',
              'btn_upload': 'Charger',
              'btn_yes_del': 'Oui, supprimer',
              'dash_subtitle': 'Apprenez à détecter les pièges numériques '
                               'étape par étape.',
              'dash_title': 'Éducation numérique',
              'js_alert_select': 'Veuillez sélectionner au moins une option\xa0'
                                 '!',
              'js_correct_msg': 'Bonne réponse !',
              'js_correct_was': "C'était exact :",
              'js_multi_choice': '(Attention\xa0: il y a plusieurs bonnes '
                                 'réponses\xa0! Sélectionnez toutes)',
              'js_single_choice': '(Sélectionnez une seule réponse)',
              'js_you_chose': 'Vous avez choisi\xa0:',
              'lbl_new_name': "Nouveau nom d'utilisateur\xa0:",
              'lbl_new_pass': 'Nouveau mot de passe\xa0:',
              'lbl_old_pass': 'Ancien mot de passe\xa0:',
              'lbl_pass': 'Mot de passe',
              'lbl_pick_file': 'Choisissez une image (jpg, png)\xa0:',
              'lbl_progress': 'Progrès',
              'lbl_question_no': 'La question',
              'lbl_report': 'Rapport détaillé\xa0:',
              'lbl_select_correct': 'Sélectionnez la bonne réponse\xa0:',
              'lbl_user': "Nom d'utilisateur",
              'link_has_acc': 'Vous avez déjà un compte ? Se connecter',
              'link_no_acc': "Vous n'avez pas de compte ? S'inscrire",
              'mod_del_title': 'Confirmation',
              'mod_pass_title': 'Réinitialiser le mot de passe',
              'mod_photo_title': 'Choisir une image',
              'mod_user_title': "Changer le nom d'utilisateur",
              'msg_bravo': 'Bravo! Voici votre résultat :',
              'msg_del_warn': 'êtes-vous sûr que vous perdrez tous vos '
                              'progrès.',
              'msg_quiz_ready': 'Êtes-vous prêt à vous tester et à obtenir le '
                                'score maximum\xa0?',
              'msg_theory_done': 'Vous avez parcouru toute la théorie\xa0!',
              'nav_dashboard': 'Tableau de bord',
              'nav_lang': 'Langue',
              'nav_logout': 'Quitter / Se déconnecter',
              'nav_scores': 'Partitions',
              'nav_settings': 'Paramètres du compte',
              'prof_avg': 'moyenne de toutes les leçons',
              'prof_title': 'Statistiques et progrès personnels',
              'prof_total': 'TOTAL',
              'quiz_page_title': 'Questionnaire:',
              'set_title': 'Configuration du compte'},
    'ro': {   'auth_login': 'Autentificare',
              'auth_register': 'Înregistrare',
              'btn_back_dash': 'Înapoi la Dashboard',
              'btn_back_menu': 'Înapoi la Meniu',
              'btn_cancel': 'Anulează',
              'btn_chg_photo': 'Schimbă poza de profil',
              'btn_chg_user': 'Schimbă username-ul',
              'btn_create': 'Creează cont',
              'btn_del_acc': 'Șterge Contul',
              'btn_enter': 'Intră în cont',
              'btn_finish_quiz': 'Vezi Rezultatele',
              'btn_main_menu': 'Meniu Principal',
              'btn_next_q': 'Următoarea',
              'btn_no': 'Nu',
              'btn_quiz': 'Rezolvă Quiz',
              'btn_restart': 'Reia Lecția',
              'btn_rst_pass': 'Resetează Parola',
              'btn_save': 'Salvează',
              'btn_start': 'Începe Lecția',
              'btn_start_quiz': 'Începe Quiz-ul',
              'btn_theory': 'Citește Teoria',
              'btn_upload': 'Încarcă',
              'btn_yes_del': 'Da, Șterge',
              'dash_subtitle': 'Învață să detectezi capcanele digitale pas cu '
                               'pas.',
              'dash_title': 'Educație Digitală',
              'js_alert_select': 'Te rog selectează cel puțin o variantă!',
              'js_correct_msg': 'Răspuns Corect!',
              'js_correct_was': 'Corect era:',
              'js_multi_choice': '(Atenție: Sunt mai multe răspunsuri corecte! '
                                 'Selectează-le pe toate)',
              'js_single_choice': '(Selectează un singur răspuns)',
              'js_you_chose': 'Tu ai ales:',
              'lbl_new_name': 'Noul username:',
              'lbl_new_pass': 'Parola Nouă:',
              'lbl_old_pass': 'Parola Veche:',
              'lbl_pass': 'Parolă',
              'lbl_pick_file': 'Alege o imagine (jpg, png):',
              'lbl_progress': 'Progres',
              'lbl_question_no': 'Întrebarea',
              'lbl_report': 'Raport Detaliat:',
              'lbl_select_correct': 'Selectează răspunsul corect:',
              'lbl_user': 'Nume utilizator',
              'link_has_acc': 'Ai deja cont? Loghează-te',
              'link_no_acc': 'Nu ai cont? Înregistrează-te',
              'mod_del_title': 'Confirmare',
              'mod_pass_title': 'Resetează Parola',
              'mod_photo_title': 'Alege Imagine',
              'mod_user_title': 'Schimbă Username-ul',
              'msg_bravo': 'Bravo! Iată rezultatul tău:',
              'msg_del_warn': 'Ești sigur? Vei pierde tot progresul.',
              'msg_quiz_ready': 'Ești pregătit să te testezi și să obții '
                                'punctajul maxim?',
              'msg_theory_done': 'Ai parcurs toată teoria!',
              'nav_dashboard': 'Dashboard',
              'nav_lang': 'Limbă',
              'nav_logout': 'Ieșire / Log out',
              'nav_scores': 'Scoruri',
              'nav_settings': 'Setări Cont',
              'prof_avg': 'media tuturor lecțiilor',
              'prof_title': 'Statistici și progres personal',
              'prof_total': 'TOTAL',
              'quiz_page_title': 'Quiz:',
              'set_title': 'Configurare cont'},
    'ru': {   'auth_login': 'Аутентификация',
              'auth_register': 'Регистрация',
              'btn_back_dash': 'Вернуться к панели управления',
              'btn_back_menu': 'Вернуться в меню',
              'btn_cancel': 'Отмена',
              'btn_chg_photo': 'Измените изображение профиля',
              'btn_chg_user': 'Изменить имя пользователя',
              'btn_create': 'Зарегистрироваться',
              'btn_del_acc': 'Удалить аккаунт',
              'btn_enter': 'Войдите в свою учетную запись',
              'btn_finish_quiz': 'Посмотреть результаты',
              'btn_main_menu': 'Главное меню',
              'btn_next_q': 'следующий',
              'btn_no': 'Нет',
              'btn_quiz': 'Решите викторину',
              'btn_restart': 'Резюме урока',
              'btn_rst_pass': 'Сбросить пароль',
              'btn_save': 'Сохранять',
              'btn_start': 'Урок начинается',
              'btn_start_quiz': 'Викторина начинается',
              'btn_theory': 'Читать теорию',
              'btn_upload': 'Нагрузка',
              'btn_yes_del': 'Да, удалить',
              'dash_subtitle': 'Научитесь шаг за шагом обнаруживать цифровые '
                               'ловушки.',
              'dash_title': 'Цифровое образование',
              'js_alert_select': 'Пожалуйста, выберите хотя бы один вариант!',
              'js_correct_msg': 'Правильный ответ!',
              'js_correct_was': 'Это было правильно:',
              'js_multi_choice': '(Внимание: правильных ответов несколько! '
                                 'Выбрать все)',
              'js_single_choice': '(Выберите только один ответ)',
              'js_you_chose': 'Вы выбрали:',
              'lbl_new_name': 'Новое имя пользователя:',
              'lbl_new_pass': 'Новый пароль:',
              'lbl_old_pass': 'Старый пароль:',
              'lbl_pass': 'Пароль',
              'lbl_pick_file': 'Выберите изображение (jpg, png):',
              'lbl_progress': 'Прогресс',
              'lbl_question_no': 'Вопрос',
              'lbl_report': 'Подробный отчет:',
              'lbl_select_correct': 'Выберите правильный ответ:',
              'lbl_user': 'Имя пользователя',
              'link_has_acc': 'У вас уже есть аккаунт? Авторизоваться',
              'link_no_acc': 'У вас нет учетной записи? Зарегистрироваться',
              'mod_del_title': 'Подтверждение',
              'mod_pass_title': 'Сбросить пароль',
              'mod_photo_title': 'Выберите изображение',
              'mod_user_title': 'Изменить имя пользователя',
              'msg_bravo': 'Браво! Вот ваш результат:',
              'msg_del_warn': 'Вы уверены, что потеряете весь прогресс?',
              'msg_quiz_ready': 'Готовы ли вы проверить себя и получить '
                                'максимальный балл?',
              'msg_theory_done': 'Вы прошли всю теорию!',
              'nav_dashboard': 'Панель управления',
              'nav_lang': 'Язык',
              'nav_logout': 'Выйти/Выйти',
              'nav_scores': 'Результаты',
              'nav_settings': 'Настройки учетной записи',
              'prof_avg': 'среднее значение всех уроков',
              'prof_title': 'Статистика и личный прогресс',
              'prof_total': 'ОБЩИЙ',
              'quiz_page_title': 'Контрольный опрос:',
              'set_title': 'Настройка учетной записи'}}