TEXTE = {
    'ro': {
        'auth_login': 'Autentificare',
        'auth_register': 'Înregistrare',
        'btn_back_dash': 'Înapoi la Dashboard',
        'btn_back_menu': 'Înapoi la Meniu',
        'btn_cancel': 'Anulează',
        'btn_chg_photo': 'Schimbă poza de profil',
        'btn_chg_user': 'Schimbă username-ul',
        'btn_create': 'Creează cont',
        'btn_del_acc': 'Șterge Contul',
        'btn_enter': 'Intră în cont',
        'btn_finish_quiz': 'Vezi Rezultatele',
        'btn_main_menu': 'Meniu Principal',
        'btn_next_q': 'Următoarea',
        'btn_no': 'Nu',
        'btn_quiz': 'Rezolvă Quiz',
        'btn_restart': 'Reia Lecția',
        'btn_rst_pass': 'Resetează Parola',
        'btn_save': 'Salvează',
        'btn_start': 'Începe Lecția',
        'btn_start_quiz': 'Începe Quiz-ul',
        'btn_theory': 'Citește Teoria',
        'btn_upload': 'Încarcă',
        'btn_yes_del': 'Da, Șterge',
        'dash_subtitle': 'Învață să detectezi capcanele digitale pas cu pas.',
        'dash_title': 'Educație Digitală',
        'js_alert_select': 'Te rog selectează cel puțin o variantă!',
        'js_correct_msg': 'Răspuns Corect!',
        'js_correct_was': 'Corect era:',
        'js_multi_choice': '(Atenție: Sunt mai multe răspunsuri corecte! Selectează-le pe toate)',
        'js_single_choice': '(Selectează un singur răspuns)',
        'js_you_chose': 'Tu ai ales:',
        'lbl_new_name': 'Noul username:',
        'lbl_new_pass': 'Parola Nouă:',
        'lbl_old_pass': 'Parola Veche:',
        'lbl_pass': 'Parolă',
        'lbl_pick_file': 'Alege o imagine (jpg, png):',
        'lbl_progress': 'Progres',
        'lbl_question_no': 'Întrebarea',
        'lbl_report': 'Raport Detaliat:',
        'lbl_select_correct': 'Selectează răspunsul corect:',
        'lbl_user': 'Nume utilizator',
        'link_has_acc': 'Ai deja cont? Loghează-te',
        'link_no_acc': 'Nu ai cont? Înregistrează-te',
        'mod_del_title': 'Confirmare',
        'mod_pass_title': 'Resetează Parola',
        'mod_photo_title': 'Alege Imagine',
        'mod_user_title': 'Schimbă Username-ul',
        'msg_bravo': 'Bravo! Iată rezultatul tău:',
        'msg_del_warn': 'Ești sigur? Vei pierde tot progresul.',
        'msg_quiz_ready': 'Ești pregătit să te testezi și să obții punctajul maxim?',
        'msg_theory_done': 'Ai parcurs toată teoria!',
        'nav_dashboard': 'Dashboard',
        'nav_lang': 'Limbă',
        'nav_logout': 'Ieșire / Log out',
        'nav_scores': 'Scoruri',
        'nav_settings': 'Setări Cont',
        'prof_avg': 'media tuturor lecțiilor',
        'prof_title': 'Statistici și progres personal',
        'prof_total': 'TOTAL',
        'quiz_page_title': 'Quiz:',
        'set_title': 'Configurare cont',
        'verify_page_title': 'Configurare Cont',
        'app_header_title': 'Educație Digitală',
        'verify_subtitle': 'Configurare cont',
        'lbl_lastname': 'Nume',
        'lbl_firstname': 'Prenume',
        'lbl_email': 'Email',
        'lbl_phone': 'Nr. de telefon',
        'btn_confirm': 'Confirmă',
        'lbl_desired_user': 'Username dorit',
        'lbl_login_input': 'Username / Email / Telefon',
        'btn_verify_data': 'Verificare Date',
        'err_name_invalid': 'Folosește doar litere (A-Z) și cratime.',
        'err_email_invalid': 'Te rog introdu o adresă de email validă.',
        'err_phone_invalid': 'Folosește doar cifre sau spații.',
        'flash_update_success': 'Datele au fost actualizate cu succes!',
        'flash_update_error': 'Eroare: Email sau Telefon deja folosit.',
        'msg_check_email': 'Cont creat! Verifică email-ul pentru link-ul de confirmare.',
        'email_subject': 'Confirmă contul ZeroPhish',
        'msg_email_confirmed': 'Email confirmat cu succes!',
        'msg_link_invalid': 'Link-ul de confirmare este invalid sau a expirat.',
        'err_email_not_verified': 'Te rog să confirmi adresa de email înainte de logare.',
        'msg_mandatory_fields': '* Câmpurile marcate sunt obligatorii.',
        'btn_back': 'Înapoi',
        'msg_login_fail': 'Date de autentificare incorecte!',
        'msg_user_exists': 'Utilizatorul, Email-ul sau Telefonul există deja.',
        'err_email_send': 'Eroare la trimiterea emailului. Contactează suportul.',
        'err_lesson_not_found': 'Lecția nu există',
        'msg_quiz_result': 'Ai obținut {score} din {total} ({percent}%)!',
        'msg_username_taken': 'Nume deja folosit.',
        'msg_username_changed': 'Username schimbat!',
        'err_no_photo': 'Nicio poză selectată.',
        'err_no_file': 'Niciun fișier.',
        'msg_photo_updated': 'Poza a fost actualizată!',
        'err_format_not_allowed': 'Format nepermis (doar jpg, png, gif, webp).',
        'err_old_password': 'Parola veche incorectă.',
        'msg_password_changed': 'Parola schimbată!',
        'msg_account_deleted': 'Cont șters.',
        'email_html_content': """
            <p>Bună <strong>@{user}</strong>,</p>
            <p>Mulțumesc pentru că te-ai înregistrat pe ZeroPhish!</p>
            <p>Pentru a putea accesa contul, te rog <a href="{link}" style="color: #7E8C69; font-weight: bold;">apasă aici</a> pentru a confirma adresa ta de email.</p>
            <br>
            <p style="color: #888; font-size: 0.9em;">Dacă nu vrei să folosești platforma sau nu așteptai acest mail de confirmare, îl poți ignora în siguranță.</p>
            <p>Toate cele bune,<br>ZeroPhish</p>
        """,
        'msg_email_changed_verify': 'Email schimbat! Te rog verifică inbox-ul pentru a confirma noua adresă.',
        'email_update_subject': 'Confirmare actualizare email ZeroPhish',
        'email_update_html_content': """
            <p>Bună <strong>@{user}</strong>,</p>
            <p>Adresa ta de email a fost actualizată!</p>
            <p>Pentru a putea accesa contul în continuare, te rog <a href="{link}" style="color: #7E8C69; font-weight: bold;">apasă aici</a> pentru a confirma adresa ta de email.</p>
            <br>
            <p style="color: #888; font-size: 0.9em;">Dacă nu vrei să folosești platforma sau nu așteptai acest mail de confirmare, îl poți ignora în siguranță.</p>
            <p>Toate cele bune,<br>ZeroPhish</p>
        """,
        'err_username_short': 'Numele de utilizator trebuie să aibă minim 3 caractere!',
        'err_password_complex': 'Parola trebuie să aibă minim 8 caractere, o cifră și un caracter special (@$!%*?&).',
        'err_complete_previous': 'Trebuie să finalizezi quiz-ul lecției anterioare pentru a debloca această lecție!',
        'badges_title': 'Realizările mele',
        'msg_no_badges': 'Finalizează quiz-uri pentru a câștiga badge-uri!',
        'badge_verified_title': 'Cont Confirmat',
        'badge_verified_desc': 'Ai verificat adresa de email.',
        'badge_first_step_title': 'Primul Pas',
        'badge_first_step_desc': 'Ai finalizat prima ta lecție.',
        'badge_student_title': 'Cursant Dedicat',
        'badge_student_desc': 'Ai parcurs toate lecțiile disponibile.',
        'badge_expert_title': 'Expert ZeroPhish',
        'badge_expert_desc': 'Ai obținut o medie de peste 90%.',
        'badge_perfect_title': 'Ochi de Vultur',
        'badge_perfect_desc': 'Ai obținut scor maxim la cel puțin un quiz.',
        'leaderboard_title': 'Clasament Global',
        'leaderboard_subtitle': 'Cei mai buni vânători de phishing',
        'lbl_user': 'Utilizator',
        'lbl_lessons_done': 'Lecții finalizate',
        'lbl_average_score': 'Scor Mediu',
        'lbl_you': '(Tu)',
    },

    'en': {
        'auth_login': 'Authentication',
        'auth_register': 'Registration',
        'btn_back_dash': 'Back to Dashboard',
        'btn_back_menu': 'Back to Home Page',
        'btn_cancel': 'Cancel',
        'btn_chg_photo': 'Change your profile picture',
        'btn_chg_user': 'Change the username',
        'btn_create': 'Create account',
        'btn_del_acc': 'Delete Account',
        'btn_enter': 'Log in to your account',
        'btn_finish_quiz': 'See Results',
        'btn_main_menu': 'Main Menu',
        'btn_next_q': 'Next',
        'btn_no': 'No',
        'btn_quiz': 'Solve the Quiz',
        'btn_restart': 'Lesson resumes',
        'btn_rst_pass': 'Reset Password',
        'btn_save': 'Save',
        'btn_start': 'Start the Lesson',
        'btn_start_quiz': 'Start the Quiz',
        'btn_theory': 'Read Theory',
        'btn_upload': 'Load',
        'btn_yes_del': 'Yes, Delete',
        'dash_subtitle': 'Learn to detect digital traps step by step.',
        'dash_title': 'Digital Education',
        'js_alert_select': 'Please select at least one option!',
        'js_correct_msg': 'Correct answer!',
        'js_correct_was': 'It was correct:',
        'js_multi_choice': '(Warning: There are more than one correct answer! Select all)',
        'js_single_choice': '(Select only one answer)',
        'js_you_chose': 'You chose:',
        'lbl_new_name': 'New username:',
        'lbl_new_pass': 'New Password:',
        'lbl_old_pass': 'Old Password:',
        'lbl_pass': 'Password',
        'lbl_pick_file': 'Choose an image (jpg, png):',
        'lbl_progress': 'Progress',
        'lbl_question_no': 'The question',
        'lbl_report': 'Detailed Report:',
        'lbl_select_correct': 'Select the correct answer:',
        'lbl_user': 'Username',
        'link_has_acc': 'Already have an account? Login',
        'link_no_acc': "Don't have an account? Sign up",
        'mod_del_title': 'Confirmation',
        'mod_pass_title': 'Reset Password',
        'mod_photo_title': 'Choose Image',
        'mod_user_title': 'Change Username',
        'msg_bravo': 'Congratulations! Here is your result:',
        'msg_del_warn': 'Are you sure? You will lose all progress.',
        'msg_quiz_ready': 'Are you ready to test yourself and get the maximum score?',
        'msg_theory_done': 'You went through all the theory!',
        'nav_dashboard': 'Dashboard',
        'nav_lang': 'Language',
        'nav_logout': 'Exit / Log out',
        'nav_scores': 'Scores',
        'nav_settings': 'Account Settings',
        'prof_avg': 'average of all lessons',
        'prof_title': 'Statistics and personal progress',
        'prof_total': 'TOTAL',
        'quiz_page_title': 'Quiz:',
        'set_title': 'Account Setup',
        'verify_page_title': 'Account Setup',
        'app_header_title': 'Digital Education',
        'verify_subtitle': 'Account configuration',
        'lbl_lastname': 'Last Name',
        'lbl_firstname': 'First Name',
        'lbl_email': 'Email',
        'lbl_phone': 'Phone Number',
        'btn_confirm': 'Confirm',
        'lbl_desired_user': 'Desired Username',
        'lbl_login_input': 'Username / Email / Phone',
        'btn_verify_data': 'Verify Data',
        'err_name_invalid': 'Use only letters (A-Z) and hyphens.',
        'err_email_invalid': 'Please enter a valid email address.',
        'err_phone_invalid': 'Use only digits and spaces.',
        'flash_update_success': 'Data updated successfully!',
        'flash_update_error': 'Error: Email or Phone is already in use.',
        'msg_check_email': 'Account created! Check your email for the confirmation link.',
        'email_subject': 'Confirm your ZeroPhish account',
        'msg_email_confirmed': 'Email successfully confirmed!',
        'msg_link_invalid': 'The confirmation link is invalid or has expired.',
        'err_email_not_verified': 'Please confirm your email address before logging in.',
        'msg_mandatory_fields': '* The fields marked are mandatory.',
        'btn_back': 'Back',
        'msg_login_fail': 'Incorrect login details!',
        'msg_user_exists': 'User, Email, or Phone already exists.',
        'err_email_send': 'Error sending email. Please contact support.',
        'err_lesson_not_found': 'Lesson does not exist',
        'msg_quiz_result': 'You got {score} out of {total} ({percent}%)!',
        'msg_username_taken': 'Username already taken.',
        'msg_username_changed': 'Username changed!',
        'err_no_photo': 'No photo selected.',
        'err_no_file': 'No file.',
        'msg_photo_updated': 'Photo updated!',
        'err_format_not_allowed': 'Format not allowed (only jpg, png, gif, webp).',
        'err_old_password': 'Old password incorrect.',
        'msg_password_changed': 'Password changed!',
        'msg_account_deleted': 'Account deleted.',
        'email_html_content': """
            <p>Hello <strong>@{user}</strong>,</p>
            <p>Thank you for registering on ZeroPhish!</p>
            <p>To access your account, please <a href="{link}" style="color: #7E8C69; font-weight: bold;">click here</a> to confirm your email address.</p>
            <br>
            <p style="color: #888; font-size: 0.9em;">If you didn't register or weren't expecting this email, you can safely ignore it.</p>
            <p>Best regards,<br>ZeroPhish</p>
        """,
        'msg_email_changed_verify': 'Email changed! Please check your inbox to confirm the new address.',
        'email_update_subject': 'Confirm ZeroPhish Email Update',
        'email_update_html_content': """
            <p>Hello <strong>@{user}</strong>,</p>
            <p>Your email address has been updated!</p>
            <p>To continue accessing your account, please <a href="{link}" style="color: #7E8C69; font-weight: bold;">click here</a> to confirm your email address.</p>
            <br>
            <p style="color: #888; font-size: 0.9em;">If you didn't expect this, you can safely ignore it.</p>
            <p>Best regards,<br>ZeroPhish</p>
        """,
        'err_username_short': 'Username must be at least 3 characters long!',
        'err_password_complex': 'Password must be at least 8 characters long, contain a digit and a special character (@$!%*?&).',
        'err_complete_previous': 'You must complete the previous lesson\'s quiz to unlock this lesson!',
        'badges_title': 'My Achievements',
        'msg_no_badges': 'Complete quizzes to earn badges!',
        'badge_verified_title': 'Verified Account',
        'badge_verified_desc': 'You have verified your email address.',
        'badge_first_step_title': 'First Step',
        'badge_first_step_desc': 'You have completed your first lesson.',
        'badge_student_title': 'Dedicated Student',
        'badge_student_desc': 'You have completed all available lessons.',
        'badge_expert_title': 'ZeroPhish Expert',
        'badge_expert_desc': 'You maintained an average score above 90%.',
        'badge_perfect_title': 'Eagle Eye',
        'badge_perfect_desc': 'You achieved a perfect score in at least one quiz.',
        'leaderboard_title': 'Global Leaderboard',
        'leaderboard_subtitle': 'The best phishing hunters',
        'lbl_user': 'User',
        'lbl_lessons_done': 'Lessons Completed',
        'lbl_average_score': 'Average Score',
        'lbl_you': '(You)',
    },

    'fr': {
        'auth_login': 'Authentification',
        'auth_register': 'Inscription',
        'btn_back_dash': 'Retour au tableau de bord',
        'btn_back_menu': 'Retour au menu',
        'btn_cancel': 'Annuler',
        'btn_chg_photo': 'Changez votre photo de profil',
        'btn_chg_user': "Changer le nom d'utilisateur",
        'btn_create': 'Créer un compte',
        'btn_del_acc': 'Supprimer le compte',
        'btn_enter': 'Connectez-vous à votre compte',
        'btn_finish_quiz': 'Voir les résultats',
        'btn_main_menu': 'Menu principal',
        'btn_next_q': 'suivant',
        'btn_no': 'Pas',
        'btn_quiz': 'Résoudre le quiz',
        'btn_restart': 'Reprise des cours',
        'btn_rst_pass': 'Réinitialiser le mot de passe',
        'btn_save': 'Sauvegarder',
        'btn_start': 'La leçon commence',
        'btn_start_quiz': 'Le quiz commence',
        'btn_theory': 'Lire la théorie',
        'btn_upload': 'Charger',
        'btn_yes_del': 'Oui, supprimer',
        'dash_subtitle': 'Apprenez à détecter les pièges numériques étape par étape.',
        'dash_title': 'Éducation numérique',
        'js_alert_select': 'Veuillez sélectionner au moins une option\xa0!',
        'js_correct_msg': 'Bonne réponse !',
        'js_correct_was': "C'était exact :",
        'js_multi_choice': '(Attention\xa0: il y a plusieurs bonnes réponses\xa0! Sélectionnez toutes)',
        'js_single_choice': '(Sélectionnez une seule réponse)',
        'js_you_chose': 'Vous avez choisi\xa0:',
        'lbl_new_name': "Nouveau nom d'utilisateur\xa0:",
        'lbl_new_pass': 'Nouveau mot de passe\xa0:',
        'lbl_old_pass': 'Ancien mot de passe\xa0:',
        'lbl_pass': 'Mot de passe',
        'lbl_pick_file': 'Choisissez une image (jpg, png)\xa0:',
        'lbl_progress': 'Progrès',
        'lbl_question_no': 'La question',
        'lbl_report': 'Rapport détaillé\xa0:',
        'lbl_select_correct': 'Sélectionnez la bonne réponse\xa0:',
        'lbl_user': "Nom d'utilisateur",
        'link_has_acc': 'Vous avez déjà un compte ? Se connecter',
        'link_no_acc': "Vous n'avez pas de compte ? S'inscrire",
        'mod_del_title': 'Confirmation',
        'mod_pass_title': 'Réinitialiser le mot de passe',
        'mod_photo_title': 'Choisir une image',
        'mod_user_title': "Changer le nom d'utilisateur",
        'msg_bravo': 'Bravo! Voici votre résultat :',
        'msg_del_warn': 'êtes-vous sûr que vous perdrez tous vos progrès.',
        'msg_quiz_ready': 'Êtes-vous prêt à vous tester et à obtenir le score maximum\xa0?',
        'msg_theory_done': 'Vous avez parcouru toute la théorie\xa0!',
        'nav_dashboard': 'Tableau de bord',
        'nav_lang': 'Langue',
        'nav_logout': 'Quitter / Se déconnecter',
        'nav_scores': 'Partitions',
        'nav_settings': 'Paramètres du compte',
        'prof_avg': 'moyenne de toutes les leçons',
        'prof_title': 'Statistiques et progrès personnels',
        'prof_total': 'TOTAL',
        'quiz_page_title': 'Questionnaire:',
        'set_title': 'Configuration du compte',
        'verify_page_title': 'Configuration du compte',
        'app_header_title': 'Éducation Numérique',
        'verify_subtitle': 'Configuration du compte',
        'lbl_lastname': 'Nom',
        'lbl_firstname': 'Prénom',
        'lbl_email': 'E-mail',
        'lbl_phone': 'Numéro de téléphone',
        'btn_confirm': 'Confirmer',
        'lbl_desired_user': 'Nom d\'utilisateur souhaité',
        'lbl_login_input': 'Nom d\'utilisateur / Email / Téléphone',
        'btn_verify_data': 'Vérifier les données',
        'err_name_invalid': 'Utilisez uniquement des lettres (A-Z) et des traits d\'union.',
        'err_email_invalid': 'Veuillez entrer une adresse e-mail valide.',
        'err_phone_invalid': 'Utilisez uniquement des chiffres et d\'espaces.',
        'flash_update_success': 'Données mises à jour avec succès !',
        'flash_update_error': 'Erreur : L\'email ou le téléphone déjà utilisé.',
        'msg_check_email': 'Compte créé ! Vérifiez votre e-mail pour le lien de confirmation.',
        'email_subject': 'Confirmez votre compte ZeroPhish',
        'msg_email_confirmed': 'E-mail confirmé avec succès !',
        'msg_link_invalid': 'Le lien de confirmation est invalide ou a expiré.',
        'err_email_not_verified': 'Veuillez confirmer votre adresse e-mail avant de vous connecter.',
        'msg_mandatory_fields': '* Les champs marqués sont obligatoires.',
        'btn_back': 'Retour',
        'msg_login_fail': 'Identifiants de connexion incorrects !',
        'msg_user_exists': 'L\'utilisateur, l\'e-mail ou le téléphone existe déjà.',
        'err_email_send': 'Erreur lors de l\'envoi de l\'e-mail. Veuillez contacter le support.',
        'err_lesson_not_found': 'La leçon n\'existe pas',
        'msg_quiz_result': 'Vous avez obtenu {score} sur {total} ({percent}%) !',
        'msg_username_taken': 'Nom d\'utilisateur déjà pris.',
        'msg_username_changed': 'Nom d\'utilisateur changé !',
        'err_no_photo': 'Aucune photo sélectionnée.',
        'err_no_file': 'Aucun fichier.',
        'msg_photo_updated': 'Photo mise à jour !',
        'err_format_not_allowed': 'Format non autorisé (uniquement jpg, png, gif, webp).',
        'err_old_password': 'Ancien mot de passe incorrect.',
        'msg_password_changed': 'Mot de passe changé !',
        'msg_account_deleted': 'Compte supprimé.',
        'email_html_content': """
            <p>Bonjour <strong>@{user}</strong>,</p>
            <p>Merci de vous être inscrit sur ZeroPhish !</p>
            <p>Pour accéder à votre compte, veuillez <a href="{link}" style="color: #7E8C69; font-weight: bold;">cliquer ici</a> pour confirmer votre adresse e-mail.</p>
            <br>
            <p style="color: #888; font-size: 0.9em;">Si vous ne vous êtes pas inscrit ou si vous n'attendiez pas cet e-mail, vous pouvez l'ignorer en toute sécurité.</p>
            <p>Cordialement,<br>ZeroPhish</p>
        """,
        'msg_email_changed_verify': 'E-mail changé ! Veuillez vérifier votre boîte de réception pour confirmer la nouvelle adresse.',
        'email_update_subject': 'Confirmez la mise à jour de l\'e-mail ZeroPhish',
        'email_update_html_content': """
            <p>Bonjour <strong>@{user}</strong>,</p>
            <p>Votre adresse e-mail a été mise à jour !</p>
            <p>Pour continuer à accéder à votre compte, veuillez <a href="{link}" style="color: #7E8C69; font-weight: bold;">cliquer ici</a> pour confirmer votre adresse e-mail.</p>
            <br>
            <p style="color: #888; font-size: 0.9em;">Si vous ne vous attendiez pas à cela, vous pouvez l'ignorer en toute sécurité.</p>
            <p>Cordialement,<br>ZeroPhish</p>
        """,
        'err_username_short': 'Le nom d\'utilisateur doit comporter au moins 3 caractères !',
        'err_password_complex': 'Le mot de passe doit comporter au moins 8 caractères, contenir un chiffre et un caractère spécial (@$!%*?&).',
        'err_complete_previous': 'Vous devez compléter le quiz de la leçon précédente pour débloquer cette leçon !',
        'badges_title': 'Mes trophées',
        'msg_no_badges': 'Terminez des quiz pour gagner des insignes !',
        'badge_verified_title': 'Compte vérifié',
        'badge_verified_desc': 'Vous avez vérifié votre adresse e-mail.',
        'badge_first_step_title': 'Premier Pas',
        'badge_first_step_desc': 'Vous avez terminé votre première leçon.',
        'badge_student_title': 'Étudiant dévoué',
        'badge_student_desc': 'Vous avez terminé toutes les leçons disponibles.',
        'badge_expert_title': 'Expert ZeroPhish',
        'badge_expert_desc': 'Vous avez obtenu une moyenne supérieure à 90%.',
        'badge_perfect_title': 'Oeil de lynx',
        'badge_perfect_desc': 'Vous avez obtenu un score de 100% à au moins un quiz.',
        'leaderboard_title': 'Classement mondial',
        'leaderboard_subtitle': 'Les meilleurs chasseurs de phishing',
        'lbl_user': 'Utilisateur',
        'lbl_lessons_done': 'Leçons terminées',
        'lbl_average_score': 'Score moyen',
        'lbl_you': '(Toi)',
    },

    'ru': {
        'auth_login': 'Аутентификация',
        'auth_register': 'Регистрация',
        'btn_back_dash': 'Вернуться к панели управления',
        'btn_back_menu': 'Вернуться в меню',
        'btn_cancel': 'Отмена',
        'btn_chg_photo': 'Измените изображение профиля',
        'btn_chg_user': 'Изменить имя пользователя',
        'btn_create': 'Зарегистрироваться',
        'btn_del_acc': 'Удалить аккаунт',
        'btn_enter': 'Войдите в свою учетную запись',
        'btn_finish_quiz': 'Посмотреть результаты',
        'btn_main_menu': 'Главное меню',
        'btn_next_q': 'следующий',
        'btn_no': 'Нет',
        'btn_quiz': 'Решите викторину',
        'btn_restart': 'Резюме урока',
        'btn_rst_pass': 'Сбросить пароль',
        'btn_save': 'Сохранять',
        'btn_start': 'Урок начинается',
        'btn_start_quiz': 'Викторина начинается',
        'btn_theory': 'Читать теорию',
        'btn_upload': 'Нагрузка',
        'btn_yes_del': 'Да, удалить',
        'dash_subtitle': 'Научитесь шаг за шагом обнаруживать цифровые ловушки.',
        'dash_title': 'Цифровое образование',
        'js_alert_select': 'Пожалуйста, выберите хотя бы один вариант!',
        'js_correct_msg': 'Правильный ответ!',
        'js_correct_was': 'Это было правильно:',
        'js_multi_choice': '(Внимание: правильных ответов несколько! Выбрать все)',
        'js_single_choice': '(Выберите только один ответ)',
        'js_you_chose': 'Вы выбрали:',
        'lbl_new_name': 'Новое имя пользователя:',
        'lbl_new_pass': 'Новый пароль:',
        'lbl_old_pass': 'Старый пароль:',
        'lbl_pass': 'Пароль',
        'lbl_pick_file': 'Выберите изображение (jpg, png):',
        'lbl_progress': 'Прогресс',
        'lbl_question_no': 'Вопрос',
        'lbl_report': 'Подробный отчет:',
        'lbl_select_correct': 'Выберите правильный ответ:',
        'lbl_user': 'Имя пользователя',
        'link_has_acc': 'У вас уже есть аккаунт? Авторизоваться',
        'link_no_acc': 'У вас нет учетной записи? Зарегистрироваться',
        'mod_del_title': 'Подтверждение',
        'mod_pass_title': 'Сбросить пароль',
        'mod_photo_title': 'Выберите изображение',
        'mod_user_title': 'Изменить имя пользователя',
        'msg_bravo': 'Браво! Вот ваш результат:',
        'msg_del_warn': 'Вы уверены, что потеряете весь прогресс?',
        'msg_quiz_ready': 'Готовы ли вы проверить себя и получить максимальный балл?',
        'msg_theory_done': 'Вы прошли всю теорию!',
        'nav_dashboard': 'Панель управления',
        'nav_lang': 'Язык',
        'nav_logout': 'Выйти/Выйти',
        'nav_scores': 'Результаты',
        'nav_settings': 'Настройки учетной записи',
        'prof_avg': 'среднее значение всех уроков',
        'prof_title': 'Статистика и личный прогресс',
        'prof_total': 'ОБЩИЙ',
        'quiz_page_title': 'Контрольный опрос:',
        'set_title': 'Настройка учетной записи',
        'verify_page_title': 'Настройка аккаунта',
        'app_header_title': 'Цифровое Образование',
        'verify_subtitle': 'Настройка учетной записи',
        'lbl_lastname': 'Фамилия',
        'lbl_firstname': 'Имя',
        'lbl_email': 'Email',
        'lbl_phone': 'Номер телефона',
        'btn_confirm': 'Подтвердить',
        'lbl_desired_user': 'Желаемое имя пользователя',
        'lbl_login_input': 'Имя пользователя / Email / Телефон',
        'btn_verify_data': 'Проверить данные',
        'err_name_invalid': 'Используйте только буквы (A-Z) и дефисы.',
        'err_email_invalid': 'Введите действительный адрес электронной почты.',
        'err_phone_invalid': 'Используйте только цифры и пробелы.',
        'flash_update_success': 'Данные успешно обновлены!',
        'flash_update_error': 'Ошибка: Email или телефон уже используются.',
        'msg_check_email': 'Аккаунт создан! Проверьте электронную почту для ссылки подтверждения.',
        'email_subject': 'Подтвердите аккаунт ZeroPhish',
        'msg_email_confirmed': 'Email успешно подтвержден!',
        'msg_link_invalid': 'Ссылка подтверждения недействительна или истекла.',
        'err_email_not_verified': 'Пожалуйста, подтвердите адрес электронной почты перед входом.',
        'msg_mandatory_fields': '* Отмеченные поля обязательны.',
        'btn_back': 'Назад',
        'msg_login_fail': 'Неверные данные для входа!',
        'msg_user_exists': 'Пользователь, Email или Телефон уже существуют.',
        'err_email_send': 'Ошибка отправки email. Пожалуйста, свяжитесь с поддержкой.',
        'err_lesson_not_found': 'Урок не существует',
        'msg_quiz_result': 'Вы набрали {score} из {total} ({percent}%)!',
        'msg_username_taken': 'Имя пользователя уже занято.',
        'msg_username_changed': 'Имя пользователя изменено!',
        'err_no_photo': 'Фото не выбрано.',
        'err_no_file': 'Нет файла.',
        'msg_photo_updated': 'Фото обновлено!',
        'err_format_not_allowed': 'Формат не поддерживается (только jpg, png, gif, webp).',
        'err_old_password': 'Старый пароль неверный.',
        'msg_password_changed': 'Пароль изменен!',
        'msg_account_deleted': 'Аккаунт удален.',
        'email_html_content': """
            <p>Здравствуйте <strong>@{user}</strong>,</p>
            <p>Спасибо за регистрацию на ZeroPhish!</p>
            <p>Чтобы получить доступ к аккаунту, пожалуйста, <a href="{link}" style="color: #7E8C69; font-weight: bold;">нажмите здесь</a> для подтверждения вашего email.</p>
            <br>
            <p style="color: #888; font-size: 0.9em;">Если вы не регистрировались или не ожидали это письмо, вы можете его проигнорировать.</p>
            <p>С наилучшими пожеланиями,<br>ZeroPhish</p>
        """,
        'msg_email_changed_verify': 'Email изменен! Пожалуйста, проверьте свою почту, чтобы подтвердить новый адрес.',
        'email_update_subject': 'Подтвердите обновление email ZeroPhish',
        'email_update_html_content': """
            <p>Здравствуйте <strong>@{user}</strong>,</p>
            <p>Ваш адрес электронной почты был обновлен!</p>
            <p>Чтобы продолжить доступ к вашему аккаунту, пожалуйста, <a href="{link}" style="color: #7E8C69; font-weight: bold;">нажмите здесь</a> для подтверждения вашего email.</p>
            <br>
            <p style="color: #888; font-size: 0.9em;">Если вы не ожидали этого, вы можете его проигнорировать.</p>
            <p>С наилучшими пожеланиями,<br>ZeroPhish</p>
        """,
        'err_username_short': 'Имя пользователя должно быть не менее 3 символов!',
        'err_password_complex': 'Пароль должен быть не менее 8 символов, содержать цифру и специальный символ (@$!%*?&).',
        'err_complete_previous': 'Вы должны пройти викторину предыдущего урока, чтобы разблокировать этот урок!',
        'badges_title': 'Мои достижения',
        'msg_no_badges': 'Проходите тесты, чтобы получать значки!',
        'badge_verified_title': 'Подтвержденный аккаунт',
        'badge_verified_desc': 'Вы подтвердили свой адрес электронной почты.',
        'badge_first_step_title': 'Первый шаг',
        'badge_first_step_desc': 'Вы завершили свой первый урок.',
        'badge_student_title': 'Преданный ученик',
        'badge_student_desc': 'Вы прошли все доступные уроки.',
        'badge_expert_title': 'Эксперт ZeroPhish',
        'badge_expert_desc': 'Ваш средний балл выше 90%.',
        'badge_perfect_title': 'Орлиный глаз',
        'badge_perfect_desc': 'Вы получили максимальный балл хотя бы за один тест.',
        'leaderboard_title': 'Глобальный рейтинг',
        'leaderboard_subtitle': 'Лучшие охотники на фишинг',
        'lbl_user': 'Пользователь',
        'lbl_lessons_done': 'Пройдено уроков',
        'lbl_average_score': 'Средний балл',
        'lbl_you': '(Tы)',
    }
}